services:
  firstservice:
    container_name: first-service
    build:
      context: ./WebApplication1/WebApplication1  # Solution directory
      dockerfile: ./Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  secondservice:
    container_name: second-service
    build:
      context: ./SecondService/SecondService  # Solution directory
      dockerfile: ./Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  thirdservice:
    container_name: third-service
    build:
      context: ./ThirdService/ThirdService  # Solution directory
      dockerfile: ./Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5678:80" # Expose Nginx on port 5678
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount the nginx.conf file
    depends_on:
      - firstservice
      - secondservice
      - thirdservice
    networks:
      - app-network

networks:
  app-network:
    driver: bridge